services:
  base:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    platform: linux/amd64
    container_name: alpacai-base
    volumes:
      - ../:/home/alpaca/workspace

  extended:
    build:
      dockerfile: Dockerfile
      context: .
      target: convagent
    platform: linux/amd64
    container_name: alpacai-extended