version: "3.8"

services:
  base:
    build:
      dockerfile: Dockerfile
      context: .
      target: base
    platform: linux/amd64
    container_name: alpacai-base

  extended:
    build:
      dockerfile: Dockerfile
      context: .
      target: convagent
    platform: linux/amd64
    container_name: alpacai-extended