site_name: AlpacAI
theme:
  name: material
  custom_dir: custom-templates
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: main.html
  - Problem Statement: problem-statement.md
  - Vision: vision.md
  - Future Directions: future-directions.md
  - Architecture: architecture.md
  - Installation: installation/prerequisites.md
  - Usage: usage.md
  - API Reference: api-reference.md
  - Contributing: contributing.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - md_in_html

plugins:
  - search